### ISSUE TITLE
Add language strings for Comment/Lexique/Repetion/Ponctuation 

### ISSUE THREAD

**Issue by ned-code** [Kury25/moodle-assignfeedback_editpdfplus#12]
Would it be possible to create language strings for "Comment Lexique Repetion Ponctuation" ( as shown in the buttons" https://www.screencast.com/t/1nNfU1NrSxQz) so that they can be changed in the Moodle language file (https://www.screencast.com/t/kfrnX85VU).  We are looking to translate these buttons into English.  Thanks very much.

**Comment by Kury25** [comment]
These strings are not in language files as you can change them in the administration area:
- for all in the administration page of the plugin
- for just one course, you can see this page : https://gitlabriset.unil.ch/Marion.Chardon/moodle-assignfeedback_editpdfplus/wikis/user-guide#configuration
It's just a set in order to see an example and test the plugin.

**Comment by ned-code** [comment]
Thanks for your response but I can't seem to access either option.

For administration page of the plugin, do you mean /admin/settings.php?section=assignfeedback_editpdfplus ? If so, I don't see any option to change the buttons.

As for configuration at the course level, is this done by clicking on the wrench icon? If so, I see this error: https://www.screencast.com/t/jBeE9wdf

Thanks for your time.

**Comment by Kury25** [comment]
Hello,

As much for me, this function was in progress in our platform, but not on the github. I push today a new version which will allow you to modify example bar from /settings.php?section=assignfeedback_editpdfplus

Indeed, from course level, it works but you have to be explicitly teacher on it. I will complete error message.

Thanks for you feedback!
